export * from "./DetailsContent";
export * from "./DetailsTabs";
export { useTableTransactionColumns } from "../constants/columns/TableTransactionColumn";

export type ApplicationDetail = {
  application_id: number;
  unique_id: string;
  date: string;
  application_date: string;
  production_date: string;
  created_at: number;
  updated_at: number;
  status: number;
  number: string;
  address: string;
  customer_name: string;
  customer_phone: string;
  customer: {
    customer_id: number;
    created_at: number;
    name: string;
    phone_number: string;
    is_active: boolean;
  };
  delivery_date: string;
  remark: string;
  sizes: string;
  color: string;
  category_name: string;
  door_lock: Product;
  default_door_lock: Product;
  default_hinge: Product;
  canopy: Product;
  transom_height_front: number;
  transom_height_back: number;
  forecaster: string;
  forecast_rate: number;
  forecast_discount_type: number;
  forecast_discount_amount: number;
  forecast_prepayment: number;
  forecast_production: number;
  forecast_accessories: number;
  forecast_services: number;
  forecast_initial: number;
  forecast_final: number;
  forecast_additional: number;
  forecast_sum: number;
  transactions: ApplicationTransaction[];
  sheathings: ApplicationSheathing[];
  baseboards: Baseboard[];
  floors: unknown[];
  windowsills: unknown[];
  lattings: unknown[];
  frameworks: unknown[];
  decorations: unknown[];
  services: ServiceItem[];
  qualities: unknown[];
  aspects: unknown[];
  author: Author;
  factory_designer: unknown;
};

type ApplicationTransaction = {
  application_transaction_id: number;
  location: string;
  door_type: string;
  veneer_type: string;
  lining_number: string;
  sheathing_style: string;
  crown_style: string;
  trim_style: string;
  up_trim_style: string;
  under_trim_style: string;
  doorway_type: number;
  doorway_thickness: number;
  booklet_number: string;
  factory_mdf_type: string;
  factory_height: number;
  factory_width: number;
  factory_mdf: number;
  factory_carcass: number;
  factory_rail: number;
  transom_or_canvas: string;
  sash: string;
  catalogue_number: string;
  pattern_form: string;
  frame_front_id: string;
  frame_back_id: string;
  opening_side: string;
  opening_direction: string;
  box_width: number;
  threshold: string;
  chamfer: string;
  quality_multiplier: number;
  height: number;
  width: number;
  quantity: number;
  volume: number;
  volume_product: number;
  transom_height_front: number;
  transom_height_back: number;
  crown_quantity: number;
  sheathing_height: number;
  sheathing_width: number;
  sheathing_thickness: number;
  sheathing_quantity: number;
  trim_height: number;
  trim_width: number;
  trim_quantity: number;
  up_trim_quantity: number;
  under_trim_quantity: number;
  filler_height: number;
  filler_width: number;
  filler_quantity: number;
  crown_height: number;
  glass_quantity: number;
  door_lock_quantity: number;
  canopy_quantity: number;
  latch_quantity: number;
  crown_width: number;
  box_service_quantity: number;
  box_service_length: number;
  product_id: number;
  sheathing_id: number;
  trim_id: number;
  up_trim_id: number;
  under_trim_id: number;
  filler_id: number;
  crown_id: number;
  glass_id: number;
  door_lock_id: number;
  canopy_id: number;
  latch_id: number;
  box_service_id: number;
  product: Product;
  sheathing: Product;
  trim: Product;
  up_trim: Product;
  under_trim: Product;
  filler: Product;
  crown: Product;
  glass: Product;
  door_lock: Product;
  canopy: Product;
  latch: Product;
  box_service: Product;
};

type Product = {
  product_id: number;
  name: string;
  product_type: string;
  price_uzs: number;
  price_usd: number;
  measure: string;
  feature: string;
  crown_coefficient: number;
  up_under_trim_height: number;
  up_under_trim_width: number;
  category_id: number;
  category: {
    category_id: number;
    name: string;
    section: number;
  };
};

type Baseboard = {
  application_baseboard_id: number;
  quantity: number;
  length: number;
  style: string;
  baseboard_id: number;
  baseboard: {
    baseboard_id: number;
    name: string;
    features: string;
    price_uzs: number;
    price_usd: number;
  };
};

type ServiceItem = {
  application_service_id: number;
  quantity: number;
  forecast: number;
  service_id: number;
  service: {
    service_id: number;
    name: string;
    features: string;
    measure: string;
    price_uzs: number;
    price_usd: number;
  };
};

type Author = {
  user_id: number;
  name: string;
  username: string;
  is_active: boolean;
  is_admin: boolean;
  is_factory: boolean;
  telegram_user_id: number;
  telegram_group_id: number;
  created_at: number;
};

type ApplicationSheathing = {
  application_sheathing_id: number;
  height: number;
  width: number;
  quantity: number;
  sheathing: Product;
};
