import { defineConfig } from 'orval';

export default defineConfig({
    // Main API configuration
    api: {
        input: {
            target: 'https://uat.jaspercrm.uz/gateway/openapi.json',
        },
        output: {
            mode: 'tags-split', // Splits generated files by OpenAPI tags
            target: 'src/shared/lib/api/generated',
            schemas: 'src/shared/lib/api/generated/model',
            client: 'react-query', // Generates React Query hooks
            httpClient: 'axios',
            clean: true, // Clean generated files before each generation
            prettier: true, // Format generated files with prettier
            override: {
                mutator: {
                    path: 'src/shared/lib/api/mutator.ts',
                    name: 'customInstance',
                },
                query: {
                    useQuery: true,
                    useMutation: true,
                    useInfiniteQuery: true,
                    signal: true, // Enables AbortController support
                    shouldExportMutatorHooks: true,
                    shouldExportHttpClient: true,
                },
                operations: {
                    // Custom operation naming strategy for your API
                    operationName: (operation: any, route: string, verb: string) => {
                        const { operationId } = operation;
                        if (operationId) {
                            // Your API uses snake_case operationIds, convert to camelCase
                            return operationId
                                .replace(/_([a-z])/g, (g: string) => g[1].toUpperCase())
                                .replace(/^[A-Z]/, (match: string) => match.toLowerCase());
                        }
                        // Fallback naming strategy
                        const pathSegments = route.split('/').filter(Boolean);
                        const resourceName = pathSegments[pathSegments.length - 1];
                        const cleanResourceName = resourceName.replace(/[{}]/g, '');
                        return `${verb}${cleanResourceName.charAt(0).toUpperCase() + cleanResourceName.slice(1)}`;
                    },
                },
                components: {
                    schemas: {
                        suffix: 'Entity', // Add 'Entity' suffix to generated types
                    },
                    responses: {
                        suffix: 'Response',
                    },
                    parameters: {
                        suffix: 'Params',
                    },
                },
                header: (info: any) => [
                    '/*',
                    ' * Generated by orval 🍃',
                    ' * Do not edit manually.',
                    ' * ' + (info.title || 'OpenAPI'),
                    ' * ' + (info.version || ''),
                    ' */',
                ],
            },
        },
        hooks: {
            afterAllFilesWrite: 'prettier --write src/shared/lib/api/generated/**/*.{ts,tsx}',
        },
    },

    // You can add more API configurations here for different services
    // Example for auth API:
    // authApi: {
    //   input: {
    //     target: 'https://auth-api.yourdomain.com/swagger.json',
    //   },
    //   output: {
    //     mode: 'tags-split',
    //     target: 'src/shared/lib/api/generated/auth',
    //     schemas: 'src/shared/lib/api/generated/auth/model',
    //     client: 'react-query',
    //     httpClient: 'axios',
    //     clean: true,
    //     prettier: true,
    //     override: {
    //       mutator: {
    //         path: 'src/shared/lib/api/auth-mutator.ts',
    //         name: 'authInstance',
    //       },
    //       query: {
    //         useQuery: true,
    //         useMutation: true,
    //         signal: true,
    //       },
    //     },
    //   },
    // },
});
